/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.server;

import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.IOException;
import java.net.ServerSocket;
import java.net.Socket;

/**
 *
 * @author hp
 */
public class Server extends javax.swing.JFrame {
    static Socket mysocket;

    public static Socket getMysocket() {
        return mysocket;
    }

    public static void setMysocket(Socket mysocket) {
        Server.mysocket = mysocket;
    }
    /**
     * Creates new form SocketServer
     */
    public Server() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        toy_identification = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        client_messages = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        toy_information_all = new javax.swing.JButton();
        toy_information = new javax.swing.JButton();
        thank_you = new javax.swing.JButton();
        toy_manufacturer = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        comm_succeded = new javax.swing.JButton();
        comm_aborted = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.LINE_AXIS));

        jPanel4.setBackground(new java.awt.Color(0, 0, 153));

        jLabel1.setFont(new java.awt.Font("Ink Free", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Planet Toys - Server");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 926, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
                .addContainerGap())
        );

        toy_identification.setBackground(new java.awt.Color(0, 0, 153));
        toy_identification.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        toy_identification.setForeground(new java.awt.Color(255, 255, 255));
        toy_identification.setText("Request Toy Identification");
        toy_identification.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toy_identificationActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("© Planet Toys 2020");

        client_messages.setEditable(false);
        client_messages.setColumns(20);
        client_messages.setRows(5);
        jScrollPane1.setViewportView(client_messages);

        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("Chat History:");

        toy_information_all.setBackground(new java.awt.Color(0, 0, 153));
        toy_information_all.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        toy_information_all.setForeground(new java.awt.Color(255, 255, 255));
        toy_information_all.setText("Request All Toy Information");
        toy_information_all.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toy_information_allActionPerformed(evt);
            }
        });

        toy_information.setBackground(new java.awt.Color(0, 0, 153));
        toy_information.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        toy_information.setForeground(new java.awt.Color(255, 255, 255));
        toy_information.setText("Request Toy Information");
        toy_information.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toy_informationActionPerformed(evt);
            }
        });

        thank_you.setBackground(new java.awt.Color(0, 0, 153));
        thank_you.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        thank_you.setForeground(new java.awt.Color(255, 255, 255));
        thank_you.setText("Request Thank you Message");
        thank_you.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thank_youActionPerformed(evt);
            }
        });

        toy_manufacturer.setBackground(new java.awt.Color(0, 0, 153));
        toy_manufacturer.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        toy_manufacturer.setForeground(new java.awt.Color(255, 255, 255));
        toy_manufacturer.setText("Request Toy Manufacturer Details");
        toy_manufacturer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toy_manufacturerActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));

        jLabel2.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Communication Information");

        comm_succeded.setBackground(new java.awt.Color(0, 153, 0));
        comm_succeded.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        comm_succeded.setForeground(new java.awt.Color(255, 255, 255));
        comm_succeded.setText("Send Communication Succeded");
        comm_succeded.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comm_succededActionPerformed(evt);
            }
        });

        comm_aborted.setBackground(new java.awt.Color(153, 0, 0));
        comm_aborted.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        comm_aborted.setForeground(new java.awt.Color(255, 255, 255));
        comm_aborted.setText("Send Communication Aborted");
        comm_aborted.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comm_abortedActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(comm_succeded, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comm_aborted, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(comm_succeded, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(comm_aborted, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 587, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(toy_information, javax.swing.GroupLayout.DEFAULT_SIZE, 292, Short.MAX_VALUE)
                                    .addComponent(toy_identification, javax.swing.GroupLayout.DEFAULT_SIZE, 292, Short.MAX_VALUE)
                                    .addComponent(toy_manufacturer, javax.swing.GroupLayout.DEFAULT_SIZE, 292, Short.MAX_VALUE)
                                    .addComponent(toy_information_all, javax.swing.GroupLayout.DEFAULT_SIZE, 292, Short.MAX_VALUE)
                                    .addComponent(thank_you, javax.swing.GroupLayout.DEFAULT_SIZE, 292, Short.MAX_VALUE)
                                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(0, 23, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(toy_identification, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(toy_information, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(toy_manufacturer, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(toy_information_all, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(thank_you, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1)))
                .addGap(12, 12, 12)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 469, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 469, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 569, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 326, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 326, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(0, 74, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void toy_identificationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toy_identificationActionPerformed
        String msgout = "Please Send the Toy Identification (toy code, toy name)";
        SocketServer s = new SocketServer(Server.getMysocket(),msgout); 
        client_messages.setText(client_messages.getText().trim() + "\n" + s.msgout);
    }//GEN-LAST:event_toy_identificationActionPerformed

    private void toy_information_allActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toy_information_allActionPerformed
        String msgout = "Please Send the  all the Toy Information";
        SocketServer s = new SocketServer(Server.getMysocket(),msgout); 
        client_messages.setText(client_messages.getText().trim() + "\n" + s.msgout);        // TODO add your handling code here:
    }//GEN-LAST:event_toy_information_allActionPerformed

    private void toy_informationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toy_informationActionPerformed
        String msgout = "Please Send the Toy Information (name, description, price, date of manufacture, batch number)";
        SocketServer s = new SocketServer(Server.getMysocket(),msgout); 
        client_messages.setText(client_messages.getText().trim() + "\n" + s.msgout);        // TODO add your handling code here:
    }//GEN-LAST:event_toy_informationActionPerformed

    private void thank_youActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_thank_youActionPerformed
         String msgout = "Please Send a Thank you Message";
        SocketServer s = new SocketServer(Server.getMysocket(),msgout); 
        client_messages.setText(client_messages.getText().trim() + "\n" + s.msgout); // TODO add your handling code here:
    }//GEN-LAST:event_thank_youActionPerformed

    private void comm_succededActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comm_succededActionPerformed
        String msgout = "Communication Succeded";
        SocketServer s = new SocketServer(Server.getMysocket(),msgout); 
        client_messages.setText(client_messages.getText().trim() + "\n" + s.msgout); // TODO add your handling code here:
    }//GEN-LAST:event_comm_succededActionPerformed

    private void toy_manufacturerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toy_manufacturerActionPerformed
        String msgout = "Please Send the Toy Manufacturer Details (company name, street address, zip-code, country)";
        SocketServer s = new SocketServer(Server.getMysocket(),msgout); 
        client_messages.setText(client_messages.getText().trim() + "\n" + s.msgout); // TODO add your handling code here:
    }//GEN-LAST:event_toy_manufacturerActionPerformed

    private void comm_abortedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comm_abortedActionPerformed
         String msgout = "Communication Aborted";
        SocketServer s = new SocketServer(Server.getMysocket(),msgout); 
        client_messages.setText(client_messages.getText().trim() + "\n" + s.msgout); // TODO add your handling code here:
    }//GEN-LAST:event_comm_abortedActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       new SocketConnect().setVisible(true);
        String msgin = "";
          Socket S;
         while(!msgin.equals("Client Exited"))
             {
                  S = Server.getMysocket();
                  if(S==null){
                     //System.out.print("Waiting for Connection...");
                     System.out.print("");
                   // S = Server.getMysocket();
                     continue;
                  }
                  else{
                      SocketServer sc = new SocketServer(S);
                      client_messages.setText(client_messages.getText().trim() + "\n" + sc.msgin);
                      msgin = sc.msgin;
                  }
                    } 
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JTextArea client_messages;
    private javax.swing.JButton comm_aborted;
    private javax.swing.JButton comm_succeded;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton thank_you;
    private javax.swing.JButton toy_identification;
    private javax.swing.JButton toy_information;
    private javax.swing.JButton toy_information_all;
    private javax.swing.JButton toy_manufacturer;
    // End of variables declaration//GEN-END:variables
}
